'use strict';
// Test C script. One entry per scene. Voice first: the scene's length comes from its narration.
//   text: narration with markers. {claimId} = a claim, spoken and shown; ^name = an anchor on the
//         next word (visual events hang on anchors). No bare digits or number words (tested).
//   cam: camera target in world px + scale (shot size), drift: direction of the 8 px/s drift
//   panels: SVG panels this scene may show once the camera has arrived (rule scene-leak)
//   chart: the scene holds a chart, so it needs exactly one level-1 element (rule level1)
//   events: [sfxType, at, probe]; at = seconds from scene start, or an anchor name (+ offset)
//   minDur: floor for scenes with little or no narration
module.exports = [
  // ---------------------------------------------------------------- hook (20–30 s)
  { id: 'hook1', chapter: 'hook', section: 'setup', shot: 'medium', layout: 'hero-number/with-unit', panels: ['hook'], cam: { x: 960, y: 560, s: 1.0 }, drift: [1, 0],
    text: 'A car loan with {balance} left, at {apr}.',
    events: [['appear', 'balance', 'hkBal'], ['reveal', 'apr', 'hkApr']] },
  { id: 'hook2', chapter: 'hook', section: 'setup', shot: 'close', layout: 'two-roads/fork', panels: ['fork'], cam: { x: 3360, y: 560, s: 1.35 }, drift: [1, 0],
    text: '^A Pay it off early, or ^B invest the extra cash?',
    events: [['transition', 0, 'cam'], ['appear', 'A', 'hkRoadA'], ['appear', 'B', 'hkRoadB']] },
  { id: 'hook3', chapter: 'hook', section: 'setup', shot: 'wide', layout: 'grid/lots', panels: ['hook'], cam: { x: 960, y: 760, s: 0.55 }, drift: [0, -1], chart: true,
    text: 'We ran both roads through all {months} months, taxing ^lots every lot.',
    events: [['transition', 0, 'cam'], ['appear', 'months', 'hkMonths'], ['compare', 'lots', 'hkLots']], hold: 0.6 },
  { id: 'hook4', chapter: 'hook', section: 'setup', shot: 'detail', layout: 'flip-point/axis', panels: ['axis'], cam: { x: 960, y: 1960, s: 2.4 }, drift: [-1, 0],
    text: 'The answer flips at an average annual return of {be_22}, compounded, in the {ord_22} tax bracket.',
    events: [['transition', 0, 'cam'], ['reveal', 'be_22', 'hkBe'], ['appear', 'ord_22', 'hkBracket']] },
  { id: 'hook5', chapter: 'hook', section: 'setup', shot: 'medium', layout: 'flip-point/axis', panels: ['axis'], cam: { x: 960, y: 2030, s: 1.0 }, drift: [1, 0],
    text: 'Below it, ^below paying off ends ahead. Above it, ^above investing does.',
    events: [['transition', 0, 'cam'], ['appear', 'below', 'hkBelow'], ['appear', 'above', 'hkAbove']] },
  // ---------------------------------------------------------------- CRUX ident
  { id: 'ident', chapter: 'ident', section: 'setup', shot: 'wide', layout: 'ident/wordmark', panels: ['ident'], cam: { x: 5960, y: 560, s: 0.5 }, drift: [1, 0],
    text: '', minDur: 3.0,
    events: [['dismiss', 0, 'dismissHook'], ['transition', 0, 'cam'], ['reveal', 0.6, 'crux']] },
  // ---------------------------------------------------------------- setup and scope
  { id: 'scope1', chapter: 'setup', section: 'setup', shot: 'wide', layout: 'canvas/statement', panels: ['scope'], cam: { x: 5960, y: 2050, s: 0.5 }, drift: [0, 1],
    text: 'Here is the ^setup setup: the rules are ^us US tax rules, and every input is ^stated stated, not forecast.',
    events: [['transition', 0, 'cam'], ['appear', 'setup', 'setupWord'], ['appear', 'us', 'usOnly'], ['appear', 'stated', 'stated']] },
  { id: 'scope2', chapter: 'setup', section: 'setup', shot: 'medium', layout: 'canvas/statement', panels: ['scope'], cam: { x: 5960, y: 2080, s: 1.0 }, drift: [1, 0],
    text: 'Loan interest is treated as ^nd not deductible, so the model ignores the new-car loan interest deduction for {ded_y0} to {ded_y1}.',
    events: [['transition', 0, 'cam'], ['appear', 'nd', 'notDed'], ['appear', 'ded_y0', 'dedY0'], ['count', 'ded_y1', 'dedY1']] },
  { id: 'facts', chapter: 'setup', section: 'setup', shot: 'medium', layout: 'hero-number/with-unit', panels: ['loan'], cam: { x: 960, y: 3300, s: 1.0 }, drift: [0, -1],
    text: 'The loan has {balance} left at {apr}, with {months} monthly payments of {payment}.',
    events: [['transition', 0, 'cam'], ['reveal', 'balance', 'fBal'], ['appear', 'apr', 'fApr'], ['count', 'months', 'fMonths'], ['count', 'payment', 'fPay']] },
  { id: 'extra', chapter: 'setup', section: 'setup', shot: 'close', layout: 'hero-number/with-badge', panels: ['fork'], cam: { x: 2760, y: 560, s: 1.6 }, drift: [1, 0],
    text: 'On top of that, {extra} a month is available. That amount is ^illu illustrative.',
    events: [['transition', 0, 'cam'], ['reveal', 'extra', 'xExtra'], ['emphasis', 'illu', 'xIllu']] },
  { id: 'roads', chapter: 'setup', section: 'setup', shot: 'medium', layout: 'two-roads/fork', panels: ['fork'], cam: { x: 3380, y: 560, s: 1.0 }, drift: [-1, 0],
    text: '^A Road A sends it to the loan. ^B Road B pays the minimum and invests it every month.',
    events: [['transition', 0, 'cam'], ['appear', 'A', 'rA'], ['appear', 'B', 'rB']] },
  { id: 'cash', chapter: 'setup', section: 'setup', shot: 'medium', layout: 'stacked-cost/absolute', panels: ['cash'], cam: { x: 3360, y: 3560, s: 1.0 }, drift: [1, 0], chart: true,
    text: 'Both roads spend ^same the same cash each month. Only the ^order order changes.',
    events: [['dismiss', 0, 'dismissFork'], ['transition', 0, 'cam'], ['appear', 0.5, 'cashCols'], ['compare', 'same', 'cashSame'], ['emphasis', 'order', 'cashOrder']] },
  // ---------------------------------------------------------------- chapter 1: the certain part
  { id: 'card1', chapter: 'ch1', section: 'setup', shot: 'wide', layout: 'chapter-card', panels: [], cam: { x: 5960, y: 3560, s: 0.5 }, drift: [1, 0],
    text: 'First, the certain part.',
    events: [['transition', 0, 'cam'], ['appear', 0.5, 'card1']] },
  { id: 'timeline', chapter: 'ch1', section: 'setup', shot: 'medium', layout: 'timeline/months', panels: ['loan'], cam: { x: 960, y: 3560, s: 1.0 }, drift: [1, 0], chart: true,
    text: 'Road A pays off the loan at month {payoff_a}. Road B keeps paying through month {horizon}.',
    events: [['transition', 0, 'cam'], ['appear', 0.6, 'tlAxis'], ['threshold-cross', 'payoff_a', 'tlA'], ['appear', 'horizon', 'tlB']] },
  { id: 'free', chapter: 'ch1', section: 'setup', shot: 'medium', layout: 'timeline/months', panels: ['loan'], cam: { x: 960, y: 3540, s: 1.0 }, drift: [-1, 0], chart: true,
    text: 'That leaves {months_free} months with no car payment on road A.',
    events: [['transition', 0, 'cam'], ['emphasis', 'months_free', 'free20']] },
  { id: 'morphInt', chapter: 'ch1', section: 'setup', shot: 'medium', layout: 'morph/months-to-dollars', panels: ['loan'], cam: { x: 930, y: 3540, s: 1.15 }, drift: [0, 0], chart: true,
    text: '', minDur: 1.2, events: [['transition', 0, 'cam']] },
  { id: 'interest', chapter: 'ch1', section: 'setup', shot: 'medium', layout: 'stacked-cost/absolute', panels: ['loan'], cam: { x: 930, y: 3540, s: 1.15 }, drift: [1, 0], chart: true,
    text: 'Interest paid falls from {int_b} to {int_a}.',
    events: [['transition', 0, 'cam'], ['count', 'int_b', 'intB'], ['count', 'int_a', 'intA']] },
  { id: 'avoided', chapter: 'ch1', section: 'setup', shot: 'medium', layout: 'hero-number/plain', panels: ['loan'], cam: { x: 900, y: 3510, s: 1.15 }, drift: [-1, 0], chart: true,
    text: 'Road A avoids {avoided} of interest. That does not depend on markets or taxes.',
    events: [['transition', 0, 'cam'], ['reveal', 'avoided', 'avd']],
    silenceBefore: 'avoided', stillAt: 'avoided', hold: 1.2 },
  { id: 'certain', chapter: 'ch1', section: 'setup', shot: 'detail', layout: 'hero-word/underline', panels: ['loan'], cam: null, drift: [1, 0],
    text: 'It is ^certain certain.',
    events: [['emphasis', 'certain', 'certainLine']] },
  { id: 'identity', chapter: 'ch1', section: 'setup', shot: 'close', layout: 'bar-compare/equal', panels: ['eq'], cam: { x: 960, y: 5140, s: 1.5 }, drift: [1, 0], chart: true,
    text: 'Because both roads spend the same cash, road A ends up investing exactly {avoided} more than road B.',
    events: [['appear', 0.823, 'eqLeft', 'decor'], ['transition', 0, 'cam'], ['appear', 1.0, 'eqRight'], ['compare', 'avoided', 'eqVal']] },
  { id: 'bridge', chapter: 'ch1', section: 'setup', shot: 'medium', layout: 'bar-compare/two', panels: ['eq'], cam: { x: 1100, y: 5120, s: 1.0 }, drift: [-1, 0], chart: true,
    text: 'So the question is narrow: can road B\'s ^head head start in the market beat a certain {avoided}, after tax?',
    events: [['appear', 0.6, 'brCertain', 'decor'], ['transition', 0, 'cam'], ['appear', 'head', 'brB'], ['reveal', 'avoided', 'brVal']] },
  // ---------------------------------------------------------------- chapter 2: tax, lot by lot
  { id: 'card2', chapter: 'ch2', section: 'setup', shot: 'medium', layout: 'chapter-card', panels: [], cam: { x: 5960, y: 5100, s: 1.0 }, drift: [1, 0],
    text: 'Second, tax, lot by lot.',
    events: [['transition', 0, 'cam'], ['appear', 0.5, 'card2']] },
  { id: 'lots1', chapter: 'ch2', section: 'setup', shot: 'wide', layout: 'grid/lots', panels: ['lots'], cam: { x: 960, y: 6700, s: 0.55 }, drift: [1, 0], chart: true,
    text: 'Each month\'s contribution is its own ^lot tax lot. At month {horizon}, everything is ^sold sold.',
    events: [['transition', 0, 'cam'], ['count', 'lot', 'ltCells'], ['appear', 'horizon', 'ltSale']] },
  { id: 'lots2', chapter: 'ch2', section: 'setup', shot: 'close', layout: 'grid/term-split', panels: ['lots'], cam: { x: 1300, y: 6620, s: 1.4 }, drift: [0, 1], chart: true,
    text: 'A lot held more than {hold_months} months at that sale is ^lt long-term. The rest are ^st short-term.',
    events: [['transition', 0, 'cam'], ['threshold-cross', 'hold_months', 'ltHold'], ['appear', 'lt', 'ltLong'], ['appear', 'st', 'ltShort']] },
  { id: 'rates', chapter: 'ch2', section: 'setup', shot: 'close', layout: 'rate-table/rows', panels: ['rates'], cam: { x: 3360, y: 6560, s: 1.4 }, drift: [1, 0],
    text: 'In the {ord_22} bracket, long-term gains are taxed at {lt_15}, and short-term gains at the full {ord_22}.',
    events: [['transition', 0, 'cam'], ['appear', 'ord_22', 'rtHead'], ['reveal', 'lt_15', 'rtLt'], ['reveal', 'ord_22#2', 'rtSt']] },
  { id: 'lots3', chapter: 'ch2', section: 'setup', shot: 'medium', layout: 'grid/two-rows', panels: ['lots'], cam: { x: 960, y: 6680, s: 1.0 }, drift: [-1, 0], chart: true,
    text: 'Road B invests from the start, so {lots_lt_b} of its {months} lots are long-term. Road A starts after the payoff: {lots_lt_a} of its {lots_a}.',
    events: [['appear', 0.99, 'l3Rows', 'decor'], ['transition', 0, 'cam'], ['count', 'lots_lt_b', 'l3B'], ['appear', 'months', 'l3Bof'], ['count', 'lots_lt_a', 'l3A'], ['appear', 'lots_a', 'l3Aof']] },
  { id: 'share', chapter: 'ch2', section: 'setup', shot: 'close', layout: 'bar-compare/share', panels: ['share'], cam: { x: 3300, y: 5160, s: 1.4 }, drift: [0, 1], chart: true,
    text: 'Near the break-even, {share_st_a} of road A\'s gains are short-term, against {share_st_b} of road B\'s.',
    events: [['appear', 1.0, 'shLegend', 'decor'], ['transition', 0, 'cam'], ['reveal', 'share_st_a', 'shA'], ['appear', 'share_st_b', 'shB']] },
  { id: 'nodeduct', chapter: 'ch2', section: 'setup', shot: 'wide', layout: 'canvas/statement', panels: [], cam: { x: 5960, y: 6700, s: 0.5 }, drift: [0, -1],
    text: 'A lot that loses money gets ^nd no deduction. ^st State income tax is left out.',
    events: [['transition', 0, 'cam'], ['appear', 'nd', 'ndLoss'], ['appear', 'st', 'ndState']] },
  // ---------------------------------------------------------------- chapter 3: where the answer flips
  { id: 'card3', chapter: 'ch3', section: 'sweep', shot: 'medium', layout: 'chapter-card', panels: [], cam: { x: 5960, y: 7700, s: 1.0 }, drift: [1, 0],
    text: 'Third, where the answer flips.',
    events: [['transition', 0, 'cam'], ['appear', 0.5, 'card3']] },
  { id: 'sw1', chapter: 'ch3', section: 'sweep', shot: 'medium', layout: 'chart/axes-intro', panels: ['sweep'], cam: { x: 3360, y: 8280, s: 1.0 }, drift: [1, 0], chart: true,
    text: 'We sweep the average annual return from {axis_lo} to {axis_hi}, compounded, in the {ord_22} bracket.',
    events: [['transition', 0, 'cam'], ['appear', 'axis_lo', 'swLo'], ['appear', 'axis_hi', 'swHi'], ['appear', 'ord_22', 'swBr']] },
  { id: 'sw2', chapter: 'ch3', section: 'sweep', shot: 'medium', layout: 'line-trend/single', panels: ['sweep'], cam: { x: 3360, y: 8330, s: 1.0 }, drift: [-1, 0], chart: true,
    text: 'The line is road B minus road A, net worth after tax at month {horizon}, and it ^rises rises with the return.',
    events: [['appear', 'horizon', 'swDef'], ['count', 'rises', 'swDraw']] },
  { id: 'sw3', chapter: 'ch3', section: 'sweep', shot: 'wide', layout: 'callout/pair', panels: ['sweep'], cam: { x: 3360, y: 8240, s: 0.58 }, drift: [0, -1], chart: true,
    text: 'At {axis_lo}, road A is ahead by {gap_lo_abs}. At {axis_hi}, road B is ahead by {gap_hi}.',
    events: [['transition', 0, 'cam'], ['appear', 'gap_lo_abs', 'swA'], ['appear', 'gap_hi', 'swB']] },
  { id: 'sw4', chapter: 'ch3', section: 'sweep', shot: 'detail', layout: 'hero-number/on-chart', panels: ['sweep'], cam: null, drift: [-1, 0], chart: true,
    text: 'Both roads end even at {be_22}.',
    events: [['transition', 0, 'cam'], ['reveal', 'be_22', 'swBe']], silenceBefore: 'be_22', stillAt: 'be_22', hold: 1.8 },
  { id: 'sw5', chapter: 'ch3', section: 'sweep', shot: 'close', layout: 'regions/two-zones', panels: ['sweep'], cam: { x: 3340, y: 8240, s: 1.35 }, drift: [1, 0], chart: true,
    text: 'Below that return, ^below paying off early ends ahead. Above it, ^above investing does.',
    events: [['transition', 0, 'cam'], ['appear', 'below', 'swBelow'], ['appear', 'above', 'swAbove']] },
  // ---------------------------------------------------------------- chapter 4: the tax bracket
  { id: 'card4', chapter: 'ch4', section: 'sweep', shot: 'medium', layout: 'chapter-card', panels: [], cam: { x: 5960, y: 9300, s: 1.0 }, drift: [1, 0],
    text: 'Fourth, the tax bracket.',
    events: [['transition', 0, 'cam'], ['appear', 0.5, 'card4']] },
  { id: 'niit', chapter: 'ch4', section: 'sweep', shot: 'close', layout: 'rate-table/rows', panels: ['rates'], cam: { x: 3360, y: 6560, s: 1.4 }, drift: [-1, 0],
    text: 'In the {ord_32} bracket we add the {niit} net investment income tax: short-term gains pay {ord_32e}, long-term gains {lt_32e}.',
    events: [['transition', 0, 'cam'], ['appear', 'ord_32', 'niHead'], ['appear', 'niit', 'niNiit'], ['reveal', 'ord_32e', 'niSt'], ['reveal', 'lt_32e', 'niLt']] },
  { id: 'morphDot', chapter: 'ch4', section: 'sweep', shot: 'wide', layout: 'morph/point-to-row', panels: ['sweep', 'dots'], cam: { x: 2200, y: 9100, s: 0.42 }, drift: [0, 0], chart: true,
    text: '', minDur: 1.2, events: [['transition', 0, 'cam']] },
  { id: 'dots', chapter: 'ch4', section: 'sweep', shot: 'medium', layout: 'dot-plot/rows', panels: ['dots'], cam: { x: 960, y: 9900, s: 1.0 }, drift: [1, 0], chart: true,
    text: 'The break-even is {be_12} in the {ord_12} bracket, and {be_22} in the {ord_22} bracket.',
    events: [['transition', 0, 'cam'], ['appear', 'be_12', 'd12'], ['appear', 'be_22', 'd22']] },
  { id: 'dots32', chapter: 'ch4', section: 'sweep', shot: 'medium', layout: 'dot-plot/rows', panels: ['dots'], cam: { x: 1000, y: 9920, s: 1.0 }, drift: [0, 1], chart: true,
    text: 'In the {ord_32} bracket, it is {be_32}.',
    events: [['appear', 'ord_32', 'd32r'], ['reveal', 'be_32', 'd32']] },
  { id: 'rises', chapter: 'ch4', section: 'sweep', shot: 'close', layout: 'annotation/arrow', panels: ['dots'], cam: { x: 1000, y: 9900, s: 1.4 }, drift: [-1, 0], chart: true,
    text: 'Higher rates on gains shrink road B\'s head start, so the threshold ^rises rises with the bracket.',
    events: [['emphasis', 'rises', 'dArrow']] },
  { id: 'below', chapter: 'ch4', section: 'sweep', shot: 'close', layout: 'dot-plot/reference', panels: ['dots'], cam: { x: 900, y: 9880, s: 1.4 }, drift: [1, 0], chart: true,
    text: 'In the {ord_12} bracket it sits below {be_0}, the loan rate as an annual yield, because road A\'s gains are mostly ^st short-term.',
    events: [['appear', 'be_0', 'dRef'], ['emphasis', 'st', 'dSt']] },
  // ---------------------------------------------------------------- chapter 5: risk and one bad sequence
  { id: 'card5', chapter: 'ch5', section: 'tension', shot: 'medium', layout: 'chapter-card', panels: [], cam: { x: 5960, y: 10900, s: 1.0 }, drift: [1, 0],
    text: 'Fifth, risk.',
    events: [['transition', 0, 'cam'], ['appear', 0.5, 'card5']] },
  { id: 'risk1', chapter: 'ch5', section: 'tension', shot: 'close', layout: 'two-column-compare', panels: ['risk'], cam: { x: 2960, y: 9900, s: 1.4 }, drift: [1, 0],
    text: 'Paying off the loan earns a certain {apr}.',
    events: [['appear', 0.857, 'rk1Head', 'decor'], ['transition', 0, 'cam'], ['reveal', 'apr', 'rkApr']] },
  { id: 'risk2', chapter: 'ch5', section: 'tension', shot: 'close', layout: 'two-column-compare', panels: ['risk'], cam: { x: 3700, y: 9900, s: 1.4 }, drift: [1, 0],
    text: 'Investing earns an average, not a ^promise promise. Our range, {axis_lo} to {axis_hi}, is illustrative.',
    events: [['appear', 0.5, 'rk2Head', 'decor'], ['transition', 0, 'cam'], ['appear', 'promise', 'rkProm'], ['appear', 'axis_lo', 'rkRange']] },
  { id: 'seq', chapter: 'ch5', section: 'tension', shot: 'wide', layout: 'timeline/strip', panels: ['seq'], cam: { x: 5560, y: 8400, s: 0.55 }, drift: [1, 0], chart: true,
    text: 'Here is an illustrative sequence: {seq_first} a year for {seq_split} months, then {seq_second} for the last {hold_months}.',
    events: [['transition', 0, 'cam'], ['appear', 'seq_first', 'sqFirst'], ['appear', 'seq_second', 'sqSecond']] },
  { id: 'race', chapter: 'ch5', section: 'tension', shot: 'medium', layout: 'line-trend/dual', panels: ['seq'], cam: { x: 5760, y: 8200, s: 1.0 }, drift: [0, -1], chart: true,
    text: 'We track net worth after tax, month by month. For {seq_split} months, both roads ^together run almost together.',
    events: [['transition', 0, 'cam'], ['appear', 0.6, 'raceAxes'], ['compare', 'together', 'raceTog']] },
  { id: 'morphGap', chapter: 'ch5', section: 'tension', shot: 'medium', layout: 'morph/lines-to-gap', panels: ['seq'], cam: { x: 5760, y: 8220, s: 1.0 }, drift: [0, 0], chart: true,
    text: '', minDur: 1.2, events: [['transition', 0, 'cam']] },
  { id: 'gap', chapter: 'ch5', section: 'tension', shot: 'close', layout: 'line-trend/gap', panels: ['seq'], cam: { x: 6000, y: 8240, s: 1.35 }, drift: [1, 0], chart: true,
    text: 'The difference, road B minus road A, ^peaks peaks, then turns negative in month {cross_month}.',
    events: [['transition', 0, 'cam'], ['appear', 'peaks', 'gapPeak'], ['threshold-cross', 'cross_month', 'gapCross']], silenceBefore: 'cross_month', stillAt: 'cross_month' },
  { id: 'downside', chapter: 'ch5', section: 'tension', shot: 'detail', layout: 'hero-number/with-delta', panels: ['seq'], cam: null, drift: [-1, 0], chart: true,
    text: 'Road A finishes {gap_end} ahead, after tax.',
    events: [['reveal', 'gap_end', 'dnEnd']], hold: 1.8 },
  { id: 'order', chapter: 'ch5', section: 'tension', shot: 'close', layout: 'hero-number/with-badge', panels: ['seq'], cam: { x: 5760, y: 9150, s: 1.4 }, drift: [1, 0],
    text: 'Over all {horizon} months, that sequence still averages {seq_avg} a year. The ^order order of the returns decided the result.',
    events: [['transition', 0, 'cam'], ['reveal', 'seq_avg', 'ordAvg'], ['emphasis', 'order', 'ordLine']] },
  // ---------------------------------------------------------------- close: a threshold, not a forecast
  { id: 'recap', chapter: 'close', section: 'resolution', shot: 'medium', layout: 'list/recap', panels: [], cam: { x: 5960, y: 11500, s: 1.0 }, drift: [1, 0],
    text: 'The payoff month and the interest avoided are ^fixed fixed. The tax depends on how long each ^lot lot is held. The ^ret return is the unknown.',
    events: [['dismiss', 0, 'dismissSeq'], ['transition', 0, 'cam'], ['appear', 'fixed', 'rc1'], ['appear', 'lot', 'rc2'], ['appear', 'ret', 'rc3']] },
  { id: 'end1', chapter: 'close', section: 'resolution', shot: 'medium', layout: 'flip-point/axis', panels: ['axis'], cam: { x: 960, y: 2030, s: 1.0 }, drift: [1, 0],
    text: 'So, in the {ord_22} bracket, the answer flips at an average annual return of {be_22}, compounded.',
    events: [['appear', 0.923, 'e1Zones', 'decor'], ['transition', 0, 'cam'], ['appear', 'ord_22', 'e1Br'], ['reveal', 'be_22', 'e1Be']], hold: 1.2 },
  { id: 'end2', chapter: 'close', section: 'resolution', shot: 'wide', layout: 'canvas/statement', panels: [], cam: { x: 5960, y: 12100, s: 0.5 }, drift: [0, 1],
    text: 'That is a ^th threshold, not a forecast. Where returns will land is not known in advance.',
    events: [['transition', 0, 'cam'], ['appear', 'th', 'e2Th']] },
  { id: 'outro', chapter: 'close', section: 'resolution', shot: 'wide', layout: 'ident/wordmark', panels: ['ident'], cam: { x: 5960, y: 560, s: 0.5 }, drift: [1, 0],
    text: '', minDur: 3.6,
    events: [['appear', 1.0, 'outroTag', 'decor'], ['transition', 0, 'cam'], ['reveal', 0.6, 'outroMark'], ['dismiss', 2.7, 'fadeAll']] },
];
