'use strict';
// Test D M2b lookdev: data for the world page (render-d/look/data.js) and the lookdev contract root (out/m2b/root):
// segment A = cold open + ident as timed in the full timeline; segment B = act 2 lines a2-7374, a2-1974inf, a2-bal74
// moved to follow A. Cues (video time of spoken numbers and words) come from the chosen takes' ASR.
//   node src/d/m2b-build.js
const fs = require('fs');
const path = require('path');
const { cues } = require('./m2-build');

const ROOT = path.join(__dirname, '..', '..');
const J = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const A_SCENES = ['co-lines', 'co-same', 'co-broke', 'co-question', 'ident'];
const B_SCENES = ['a2-7374', 'a2-1974inf', 'a2-bal74'];
const CLAIMS = ['y1991', 'y1973', 'y1974', 'loss1974', 'inf1974', 'bal74'];

function main() {
  const tl = J('out/timeline.json'), script = J('out/script.json'), claimsAll = J('out/claims.json').claims;
  const model = J('out/model.json');
  const takesArr = J('out/voice/takes.json').takes, el = J('out/voice/el-takes.json');
  const takes = Object.fromEntries(takesArr.map((t) => [t.id, { ...t, name: path.basename(t.raw, '.mp3') }]));
  const A = tl.scenes.filter((s) => A_SCENES.includes(s.id));
  const aEnd = A[A.length - 1].start + A[A.length - 1].dur;
  const B0 = tl.scenes.find((s) => s.id === B_SCENES[0]).start;
  const off = +(aEnd - B0).toFixed(3);
  const B = tl.scenes.filter((s) => B_SCENES.includes(s.id)).map((s) => ({ ...s, start: +(s.start + off).toFixed(3), srcStart: s.start }));
  const scenes = [...A.map((s) => ({ ...s, srcStart: s.start })), ...B];
  const total = +(B[B.length - 1].start + B[B.length - 1].dur).toFixed(3);
  const sentences = script.sentences.filter((l) => scenes.some((s) => s.id === l.scene)).map((l) => {
    const sh = B_SCENES.includes(l.scene) ? off : 0;
    return { ...l, start: +(l.start + sh).toFixed(3), end: +(l.end + sh).toFixed(3), srcStart: l.start };
  });
  const cueMap = cues(sentences, takes, el);
  // yearly data 1966..1995
  const rows = fs.readFileSync(path.join(ROOT, 'data/normalized/annual.csv'), 'utf8').trim().split('\n').slice(1).map((r) => r.split(',').map(Number));
  const yr = {};
  for (const [y, s, b, i] of rows) yr[y] = { s, b, i };
  const years = [];
  for (let y = 1966; y <= 1995; y++) {
    const r = 0.6 * yr[y].s + 0.4 * yr[y].b;
    years.push({ y, nominal: +r.toFixed(5), inflation: yr[y].i, real: +((1 + r) / (1 + yr[y].i) - 1).toFixed(5) });
  }
  const p66 = model.paths['1966'], pm = model.paths.mirror;
  const data = {
    total, off, scenes, sentences: sentences.map((l) => ({ id: l.id, scene: l.scene, text: l.text, start: l.start, end: l.end })), cues: cueMap,
    years, balance: { '1966': [model.initial, ...p66.endReal], mirror: [model.initial, ...pm.endReal] }, depleted: p66.depletedYear,
    claims: Object.fromEntries(claimsAll.filter((c) => CLAIMS.includes(c.claimId)).map((c) => [c.claimId, { display: c.display, basis: c.basis || null, character: c.character || null }])),
  };
  fs.writeFileSync(path.join(ROOT, 'render-d/look/data.js'), '// generated by src/d/m2b-build.js\nwindow.DATA = ' + JSON.stringify(data) + ';\n');
  console.log('lookdev total', total, 'offset', off, 'scenes', scenes.length, 'sentences', sentences.length);
  for (const k of Object.keys(cueMap).filter((k) => /\d/.test(k))) console.log(' cue', k, cueMap[k]);
  return { data, sentences, scenes, tl, claimsAll, script };
}

if (require.main === module) main();
module.exports = { main, A_SCENES, B_SCENES, CLAIMS };
