'use strict';
// Test D M2c: data for the world page (render-d/look/data-m2c.js) and the animatic root (out/m2c/root).
// Timeline: cold open + ident as in the full timeline; then the act-1 lines that teach the world and the act-2 lines of
// 1973-74, packed one after the other with their final clip lengths (no stretching).
//   node src/d/m2c-build.js
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..', '..');
const J = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const A_SCENES = ['co-lines', 'co-same', 'co-broke', 'co-question', 'ident'];
const B_LINES = ['a1-est.1', 'a1-start.1', 'a1-start.2', 'a1-rule.1', 'a1-rule.2', 'a1-raise.1', 'a1-raise.2', 'a1-horizon.1', 'a1-horizon.2', 'a1-horizon.3',
  'a1-mirror-in.1', 'a1-mirror-rule.1', 'a1-mirror-rule.2', 'a1-mirror-rule.3'];
const C_LINES = ['a2-7374.1', 'a2-1974inf.1', 'a2-bal74.1', 'a2-bal74m.1'];
const CLAIMS = ['y1991', 'initial', 'wd1', 'ax1966', 'ax1995', 'y1966', 'y1995', 'y1973', 'y1974', 'loss1974', 'inf1974', 'bal74', 'bal74m'];

function main() {
  const tl = J('out/timeline.json'), claimsAll = J('out/claims.json').claims, model = J('out/model.json');
  const sents = J('out/voice/sentences.json').sentences;
  const takesArr = J('out/voice/takes.json').takes, el = J('out/voice/el-takes.json');
  const takes = Object.fromEntries(takesArr.map((t) => [t.id, { ...t, name: path.basename(t.raw, '.mp3') }]));
  const dur = (id) => +execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', path.join(ROOT, takes[id].final)]).toString().trim();
  const A = tl.scenes.filter((s) => A_SCENES.includes(s.id));
  const aEnd = +(A[A.length - 1].start + A[A.length - 1].dur).toFixed(3);
  const script = J('out/script.json').sentences;
  const sentences = script.filter((l) => A_SCENES.includes(l.scene)).map((l) => ({ id: l.id, scene: l.scene, text: l.text, start: l.start, end: l.end, act: 'cold-open' }));
  const shots = A.map((s) => ({ id: s.id, start: s.start, act: s.act }));
  let cur = aEnd + 0.9;
  let lastScene = null;
  for (const [ids, act, lead] of [[B_LINES, 'act1', 0.9], [C_LINES, 'act2', 1.4]]) {
    cur += lead - 0.9;
    for (const id of ids) {
      const s = sents.find((x) => x.id === id);
      if (lastScene && s.scene !== lastScene) cur += 0.5;
      const d = dur(id);
      shots.push({ id, start: +(cur - (id === ids[0] ? lead : 0.3)).toFixed(3), act });
      sentences.push({ id, scene: s.scene, text: s.text, start: +cur.toFixed(3), end: +(cur + d).toFixed(3), act });
      cur += d + 0.45; lastScene = s.scene;
    }
  }
  const total = +(cur + 1.2).toFixed(3);
  // shots end where the next one starts; a shot starts 0.3 s before its line (the cut leads the voice)
  for (let i = 0; i < shots.length; i++) { if (i && shots[i].start < shots[i - 1].start + 1.2) shots[i].start = +(shots[i - 1].start + 1.2).toFixed(3); }
  for (let i = 0; i < shots.length; i++) shots[i].dur = +((i + 1 < shots.length ? shots[i + 1].start : total) - shots[i].start).toFixed(3);
  // cues: video time of each word = line start + 30 ms + ASR word start of the chosen take
  const cues = {};
  for (const s of sentences) {
    const tk = takes[s.id]; const rec = tk && el[tk.name];
    if (!rec) continue;
    for (const w of rec.words) { const k = `${s.id}|${w.w.toLowerCase().replace(/[^a-z0-9$.,%]/g, '').replace(/[.,]$/, '')}`; if (!(k in cues)) cues[k] = +(s.start + 0.03 + w.start).toFixed(3); }
  }
  const rows = fs.readFileSync(path.join(ROOT, 'data/normalized/annual.csv'), 'utf8').trim().split('\n').slice(1).map((r) => r.split(',').map(Number));
  const yr = {}; for (const [y, st, b, i] of rows) yr[y] = { st, b, i };
  const years = []; for (let y = 1966; y <= 1995; y++) { const r = 0.6 * yr[y].st + 0.4 * yr[y].b; years.push({ y, nominal: +r.toFixed(5), inflation: yr[y].i, real: +((1 + r) / (1 + yr[y].i) - 1).toFixed(5) }); }
  const p66 = model.paths['1966'], pm = model.paths.mirror;
  const data = { total, coldOpenEnd: aEnd, shots, sentences, cues, years,
    balance: { '1966': [model.initial, ...p66.endReal], mirror: [model.initial, ...pm.endReal] }, withdrawal: p66.withdrawals, depleted: p66.depletedYear,
    claims: Object.fromEntries(claimsAll.filter((c) => CLAIMS.includes(c.claimId)).map((c) => [c.claimId, { display: c.display, basis: c.basis || null, illustrative: !!c.illustrative }])) };
  fs.writeFileSync(path.join(ROOT, 'render-d/look/data-m2c.js'), '// generated by src/d/m2c-build.js\nwindow.DATA = ' + JSON.stringify(data) + ';\n');
  console.log('animatic total', total, 'shots', shots.length, 'sentences', sentences.length);
  return { data, sentences, shots, claimsAll, tl, aEnd };
}

if (require.main === module) main();
module.exports = { main };
